# Generated by Django 5.2.4 on 2026-02-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhóm dịch vụ')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(verbose_name='Mô tả ngắn')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá tiền (VNĐ)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Hình ảnh minh họa')),
                ('duration', models.IntegerField(default=60, verbose_name='Thời lượng (phút)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='spa_app.category', verbose_name='Nhóm dịch vụ')),
            ],
        ),
    ]
