# Generated by Django 5.2.4 on 2026-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0002_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='contact/', verbose_name='Mã QR thanh toán'),
        ),
    ]
