# Generated by Django 5.2.4 on 2026-02-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0003_contactinfo_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('booker_name', models.CharField(max_length=200, verbose_name='Người đặt lịch')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('discount_percent', models.FloatField(default=0, verbose_name='Giảm giá (%)')),
                ('payment_method', models.CharField(choices=[('none', 'Chưa thanh toán'), ('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], default='none', max_length=20, verbose_name='PT Thanh toán')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đặt')),
                ('services', models.ManyToManyField(to='spa_app.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Đơn đặt lịch',
                'verbose_name_plural': 'Danh sách đơn đặt lịch',
                'ordering': ['-created_at'],
            },
        ),
    ]
