# Generated by Django 5.2.4 on 2026-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sản phẩm/Mỹ phẩm'),
        ),
        migrations.AddField(
            model_name='booking',
            name='product_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá sản phẩm'),
        ),
    ]
