# Generated by Django 5.2.4 on 2026-02-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0005_booking_product_name_booking_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian sửa'),
        ),
    ]
