# Generated by Django 5.2.4 on 2026-02-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0006_booking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='product_discount_percent',
            field=models.FloatField(default=0, verbose_name='Giảm giá sản phẩm (%)'),
        ),
    ]
